export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  REFRESH_INVALID = 'REFRESH_INVALID',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  SLUG_TAKEN = 'SLUG_TAKEN',
  LOCATION_OUTSIDE_DISTRICT = 'LOCATION_OUTSIDE_DISTRICT',
  MEDIA_URL_INVALID = 'MEDIA_URL_INVALID',
  RATE_LIMITED = 'RATE_LIMITED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  DOMAIN_ERROR = 'DOMAIN_ERROR',
}
